server:
  port: 51001
swagger:
  docket:
    用户中心:
      title: 用户中心
      version: 1.2.0
      basePackage: com.zzn.grou.swagger.controller1
      contact:
        email: m18398079257_1@163.com
        name: zengzhangni
        url: http://baidu.com/
      description: 用户分组
      excludePath: /error/**
    测试:
      title: 测试
      version: 1.2.0
      basePackage: com.zzn.grou.swagger.controller2
      contact:
        email: m18398079257_1@163.com
        name: zengzhangni
        url: http://baidu.com/
      description: 测试分组
      excludePath: /error/**